name = "kouyu-worker"
compatibility_date = "2026-10-03"
main = "worker/index.mjs"
workers_dev = true
preview_urls = false

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = [ "/api/*" ]

[[d1_databases]]
binding = "DB"
database_name = "kouyu-production"
database_id = "42f7f5ca-cdf4-46c9-99b6-ac91a10dec65"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "AUDIO"
id = "6232bcb0af7945f0bca20ca6cdb711ef"

[secrets]
required = [ "SESSION_SECRET", "TEACHER_TOKEN" ]
