import React,{useEffect,useRef,useState,useReducer} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,AudioLines,BarChart3,BookOpen,Bookmark,CheckCircle2,ChevronRight,Headphones,LayoutDashboard,Leaf,Library,Menu,Settings2,ShieldCheck,Sparkles,Target,UsersRound,X} from 'lucide-react';
import {createState,loadState,reducer} from './model.mjs';
import {Modal} from './ui.jsx';
import {Home,Diagnostic,Path,LibraryPage,Tasks,Report,Words} from './student.jsx';
import {Practice} from './practice.jsx';
import {TeacherHome,Manage,Reviews,Activity,TaskModal} from './teacher.jsx';
import './styles.css';
const studentNav=[['home','今日学习',LayoutDashboard],['path','我的学习路径',Target],['library','练习资源库',Library],['tasks','课堂任务',BookOpen],['report','学习记录',BarChart3],['words','我的生词本',Bookmark]];
const teacherNav=[['teacher','教学概览',LayoutDashboard],['manage','任务管理',BookOpen],['reviews','录音批阅',Headphones],['resources','教学资源',Library],['activity','课堂活动',UsersRound]];
function SettingsModal({onClose}){return <Modal title="关于这个学习空间" onClose={onClose}><div className="settings-body"><span className="brand-icon"><AudioLines/></span><h3>口语 · Speaking Lab</h3><p>以真实交流为目标的英语口语练习工具。</p>{[[CheckCircle2,'可以体验','诊断推荐、合成语音示范、真实录音与回放、生词收藏、文字情景练习、任务发布与本地批阅。'],[ShieldCheck,'数据保存在当前浏览器','进度保存在本地，录音不会上传。切换设备不会同步；清除网站数据会移除这些记录。'],[UsersRound,'角色切换用于设计体验','目前未接入账号与权限。正式版需完成教师身份验证、服务器权限校验及班级隔离。'],[Sparkles,'后续服务','真实 AI 对话、语音评分与多人在线课堂尚未接入，不展示模拟能力分数。']].map(([Icon,title,text])=><div className="settings-item" key={title}><Icon/><div><b>{title}</b><p>{text}</p></div></div>)}</div></Modal>;}
function App(){
  const [state,dispatch]=useReducer(reducer,null,()=>{try{return loadState(localStorage.getItem('kouyu-v2'));}catch{return createState();}});
  const [role,setRole]=useState('student'),[page,setPage]=useState('home'),[practiceStep,setPracticeStep]=useState('listening'),[menu,setMenu]=useState(false),[modal,setModal]=useState(null),[toast,setToast]=useState(''),[storageError,setStorageError]=useState(false);const timer=useRef();
  const notify=text=>{clearTimeout(timer.current);setToast(text);timer.current=setTimeout(()=>setToast(''),4000);};
  useEffect(()=>{try{localStorage.setItem('kouyu-v2',JSON.stringify(state));setStorageError(false);}catch{setStorageError(true);}},[state]);useEffect(()=>()=>clearTimeout(timer.current),[]);
  const go=(target,step='listening')=>{window.speechSynthesis?.cancel();setPage(target);setPracticeStep(step);setMenu(false);window.scrollTo({top:0});};
  const select=id=>{dispatch({type:'select',id});go('practice');};const onCreate=id=>setModal({type:'task',lesson:id});const nav=role==='student'?studentNav:teacherNav;const context={state,dispatch,go,select,notify,onCreate};
  const pages={home:()=> <Home {...context}/>,diagnostic:()=> <Diagnostic {...context}/>,path:()=> <Path {...context}/>,library:()=> <LibraryPage {...context}/>,practice:()=> <Practice key={`${state.activeLesson}-${practiceStep}`} {...context} initialStep={practiceStep}/>,tasks:()=> <Tasks {...context}/>,report:()=> <Report {...context}/>,words:()=> <Words {...context}/>,teacher:()=> <TeacherHome {...context}/>,manage:()=> <Manage {...context}/>,reviews:()=> <Reviews {...context}/>,resources:()=> <LibraryPage {...context} teacher/>,activity:()=> <Activity/>};
  const title=nav.find(n=>n[0]===page)?.[1]||({diagnostic:'基础诊断',practice:'场景练习'})[page];
  return <div className="app"><aside className={`sidebar ${menu?'open':''}`}><a href="#" className="brand" onClick={e=>{e.preventDefault();go(role==='student'?'home':'teacher');}}><span className="brand-icon"><AudioLines size={25}/></span><span>口语<small>SPEAKING LAB</small></span></a><button className="mobile-close icon-btn" aria-label="关闭菜单" onClick={()=>setMenu(false)}><X/></button><div className="workspace-label">{role==='student'?'我的学习空间':'教师工作台'}<span>本地体验</span></div><nav aria-label="主导航">{nav.map(([id,label,Icon])=><button key={id} aria-current={page===id?'page':undefined} className={page===id?'active':''} onClick={()=>go(id)}><Icon size={19}/>{label}{id==='tasks'&&<span className="nav-count">{state.tasks.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="sidebar-quote"><Leaf size={22}/><p>A little courage.<br/>A little practice.<br/><b>A new voice.</b></p><span>每一天，勇敢多一点。</span></div><button className="settings-link" onClick={()=>setModal({type:'settings'})}><Settings2 size={17}/>设置与说明</button><div className="profile"><span className="avatar">{role==='student'?'学':'师'}</span><div><b>{role==='student'?'我的练习空间':'教学演示空间'}</b><small>记录保存在本浏览器</small></div></div></div></aside>{menu&&<button className="scrim" aria-label="关闭导航遮罩" onClick={()=>setMenu(false)}/>}
    <main><header className="topbar"><div className="breadcrumb"><button className="menu-btn icon-btn" aria-label="打开导航" onClick={()=>setMenu(true)}><Menu/></button><span>{role==='student'?'学习空间':'教学空间'}</span><ChevronRight size={13}/><b>{title}</b></div><div className="topbar-right"><span className="local-badge"><span/>设计体验版</span><div className="role-switch" aria-label="体验角色">{[['student','学生端'],['teacher','教师端']].map(([id,label])=><button key={id} className={role===id?'active':''} aria-pressed={role===id} onClick={()=>{setRole(id);go(id==='student'?'home':'teacher');}}>{label}</button>)}</div></div></header>{storageError&&<div className="storage-error" role="alert">浏览器存储不可用，当前进度在刷新后可能丢失。请允许网站存储。</div>}<div className="content">{pages[page]?.()}</div><footer className="app-footer"><span>口语 · SPEAKING LAB</span><span>让表达发生，让进步看得见。</span><button onClick={()=>setModal({type:'settings'})}>数据与服务说明<ArrowUpRight size={13}/></button></footer></main>
    {modal?.type==='task'&&<TaskModal lessonId={modal.lesson} dispatch={dispatch} notify={notify} onClose={()=>setModal(null)}/>} {modal?.type==='settings'&&<SettingsModal onClose={()=>setModal(null)}/>} {toast&&<div className="toast" role="status"><CheckCircle2 size={18}/>{toast}</div>}
  </div>;
}
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
