import React,{useEffect,useRef,useState,useReducer} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,AudioLines,BarChart3,BookOpen,Bookmark,CheckCircle2,ChevronRight,Cloud,Headphones,KeyRound,LayoutDashboard,Leaf,Library,LogOut,Menu,Settings2,ShieldCheck,Sparkles,Target,UsersRound,X} from 'lucide-react';
import {createState,loadState,reducer} from './model.mjs';
import {loadCloudState,loginTeacher,logoutTeacher,syncEvent} from './api.js';
import {Button,Modal} from './ui.jsx';
import {Home,Diagnostic,Path,LibraryPage,Tasks,Report,Words} from './student.jsx';
import {Practice} from './practice.jsx';
import {TeacherHome,Manage,Reviews,Activity,TaskModal} from './teacher.jsx';
import './styles.css';
import './cloud.css';
const studentNav=[['home','今日学习',LayoutDashboard],['path','我的学习路径',Target],['library','练习资源库',Library],['tasks','课堂任务',BookOpen],['report','学习记录',BarChart3],['words','我的生词本',Bookmark]];
const teacherNav=[['teacher','教学概览',LayoutDashboard],['manage','任务管理',BookOpen],['reviews','录音批阅',Headphones],['resources','教学资源',Library],['activity','课堂活动',UsersRound]];
function SettingsModal({onClose,teacher,onLogout}){return <Modal title="关于这个学习空间" onClose={onClose}><div className="settings-body"><span className="brand-icon"><AudioLines/></span><h3>口语 · Speaking Lab</h3><p>以真实交流为目标的英语口语练习工具。</p>{[[Cloud,'Cloudflare 云端数据','学习进度、班级任务、作业提交和教师点评保存在 D1，可在同一浏览器会话持续同步。'],[ShieldCheck,'录音仍留在当前设备','音频 Blob 保存在 IndexedDB；D1 仅保存录音元数据。跨设备音频同步需要后续接入 R2。'],[UsersRound,'教师操作受保护','发布任务和批改作业必须先使用教师口令建立加密会话，权限由 Worker 在服务端校验。'],[Sparkles,'AI 服务边界','SiliconFlow 接口由 Worker 代理，API Key 不会发送到浏览器；未配置时不会伪造 AI 结果。']].map(([Icon,title,text])=><div className="settings-item" key={title}><Icon/><div><b>{title}</b><p>{text}</p></div></div>)}{teacher&&<Button kind="outline full" onClick={onLogout}><LogOut size={16}/>退出教师会话</Button>}</div></Modal>;}
function TeacherLoginModal({onClose,onSuccess}){const [token,setToken]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(e){e.preventDefault();setBusy(true);setError('');try{await loginTeacher(token);onSuccess();}catch(err){setError(err.status===401?'教师口令不正确，请重试。':'登录服务暂时不可用，请稍后重试。');}finally{setBusy(false);}}return <Modal title="进入教师工作台" onClose={onClose}><form onSubmit={submit}><div className="login-mark"><KeyRound size={28}/><div><b>教师身份验证</b><p>口令只发送给 Cloudflare Worker，并由服务端 Secret 校验。</p></div></div><label className="field" htmlFor="teacher-token">教师口令<input id="teacher-token" type="password" autoFocus required autoComplete="current-password" value={token} onChange={e=>setToken(e.target.value)} placeholder="请输入教师口令"/></label>{error&&<p className="error" role="alert">{error}</p>}<div className="form-footer"><Button kind="ghost" type="button" onClick={onClose}>取消</Button><Button type="submit" disabled={busy||!token}>{busy?'正在验证…':'进入教师端'}</Button></div></form></Modal>;}
function App(){
  const [state,localDispatch]=useReducer(reducer,null,()=>{try{return loadState(localStorage.getItem('kouyu-v2'));}catch{return createState();}});
  const [role,setRole]=useState('student'),[page,setPage]=useState('home'),[practiceStep,setPracticeStep]=useState('listening'),[menu,setMenu]=useState(false),[modal,setModal]=useState(null),[toast,setToast]=useState(''),[storageError,setStorageError]=useState(false),[cloud,setCloud]=useState('loading'),[teacher,setTeacher]=useState(false);const timer=useRef(),syncQueue=useRef(Promise.resolve());
  const notify=text=>{clearTimeout(timer.current);setToast(text);timer.current=setTimeout(()=>setToast(''),4000);};
  const dispatch=action=>{localDispatch(action);if(action.type==='hydrate')return;syncQueue.current=syncQueue.current.then(()=>syncEvent(action)).then(()=>setCloud('ready')).catch(()=>{setCloud('error');notify('云端同步失败，操作已暂存在本机');});};
  useEffect(()=>{let active=true;loadCloudState().then(data=>{if(!active)return;localDispatch({type:'hydrate',state:data.state});setTeacher(Boolean(data.session?.teacher));setCloud('ready');}).catch(()=>active&&setCloud('error'));return()=>{active=false;};},[]);
  useEffect(()=>{try{localStorage.setItem('kouyu-v2',JSON.stringify(state));setStorageError(false);}catch{setStorageError(true);}},[state]);useEffect(()=>()=>clearTimeout(timer.current),[]);
  const go=(target,step='listening')=>{window.speechSynthesis?.cancel();setPage(target);setPracticeStep(step);setMenu(false);window.scrollTo({top:0});};
  const chooseRole=id=>{if(id==='teacher'&&!teacher){setModal({type:'teacher-login'});return;}setRole(id);go(id==='student'?'home':'teacher');loadCloudState(id).then(data=>localDispatch({type:'hydrate',state:data.state})).catch(()=>setCloud('error'));};
  const finishTeacherLogin=()=>{setTeacher(true);setRole('teacher');setModal(null);go('teacher');loadCloudState('teacher').then(data=>localDispatch({type:'hydrate',state:data.state})).catch(()=>setCloud('error'));notify('教师身份验证成功');};
  const signOutTeacher=async()=>{try{await logoutTeacher();}finally{setTeacher(false);setRole('student');setModal(null);go('home');notify('已退出教师会话');}};
  const select=id=>{dispatch({type:'select',id});go('practice');};const onCreate=id=>setModal({type:'task',lesson:id});const nav=role==='student'?studentNav:teacherNav;const context={state,dispatch,go,select,notify,onCreate};
  const pages={home:()=> <Home {...context}/>,diagnostic:()=> <Diagnostic {...context}/>,path:()=> <Path {...context}/>,library:()=> <LibraryPage {...context}/>,practice:()=> <Practice key={`${state.activeLesson}-${practiceStep}`} {...context} initialStep={practiceStep}/>,tasks:()=> <Tasks {...context}/>,report:()=> <Report {...context}/>,words:()=> <Words {...context}/>,teacher:()=> <TeacherHome {...context}/>,manage:()=> <Manage {...context}/>,reviews:()=> <Reviews {...context}/>,resources:()=> <LibraryPage {...context} teacher/>,activity:()=> <Activity/>};
  const title=nav.find(n=>n[0]===page)?.[1]||({diagnostic:'基础诊断',practice:'场景练习'})[page];
  return <div className="app"><aside className={`sidebar ${menu?'open':''}`}><a href="#" className="brand" onClick={e=>{e.preventDefault();go(role==='student'?'home':'teacher');}}><span className="brand-icon"><AudioLines size={25}/></span><span>口语<small>SPEAKING LAB</small></span></a><button className="mobile-close icon-btn" aria-label="关闭菜单" onClick={()=>setMenu(false)}><X/></button><div className="workspace-label">{role==='student'?'我的学习空间':'教师工作台'}<span>{cloud==='ready'?'D1 云端同步':cloud==='loading'?'正在连接云端':'本机暂存'}</span></div><nav aria-label="主导航">{nav.map(([id,label,Icon])=><button key={id} aria-current={page===id?'page':undefined} className={page===id?'active':''} onClick={()=>go(id)}><Icon size={19}/>{label}{id==='tasks'&&<span className="nav-count">{state.tasks.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="sidebar-quote"><Leaf size={22}/><p>A little courage.<br/>A little practice.<br/><b>A new voice.</b></p><span>每一天，勇敢多一点。</span></div><button className="settings-link" onClick={()=>setModal({type:'settings'})}><Settings2 size={17}/>设置与说明</button><div className="profile"><span className="avatar">{role==='student'?'学':'师'}</span><div><b>{role==='student'?'我的练习空间':'教师工作台'}</b><small>{cloud==='ready'?'数据由 Cloudflare D1 保存':'等待云端同步'}</small></div></div></div></aside>{menu&&<button className="scrim" aria-label="关闭导航遮罩" onClick={()=>setMenu(false)}/>}
    <main><header className="topbar"><div className="breadcrumb"><button className="menu-btn icon-btn" aria-label="打开导航" onClick={()=>setMenu(true)}><Menu/></button><span>{role==='student'?'学习空间':'教学空间'}</span><ChevronRight size={13}/><b>{title}</b></div><div className="topbar-right"><span className={`local-badge ${cloud==='error'?'sync-error':''}`}><span/>{cloud==='ready'?'D1 已同步':cloud==='loading'?'正在同步':'同步待恢复'}</span><div className="role-switch" aria-label="体验角色">{[['student','学生端'],['teacher','教师端']].map(([id,label])=><button key={id} className={role===id?'active':''} aria-pressed={role===id} onClick={()=>chooseRole(id)}>{label}</button>)}</div></div></header>{storageError&&<div className="storage-error" role="alert">浏览器存储不可用，当前进度在刷新后可能丢失。请允许网站存储。</div>}{cloud==='error'&&<div className="storage-error" role="alert">暂时无法连接 D1，当前操作会保存在本机；恢复连接后请刷新页面。</div>}<div className="content">{pages[page]?.()}</div><footer className="app-footer"><span>口语 · SPEAKING LAB</span><span>让表达发生，让进步看得见。</span><button onClick={()=>setModal({type:'settings'})}>数据与服务说明<ArrowUpRight size={13}/></button></footer></main>
    {modal?.type==='task'&&<TaskModal lessonId={modal.lesson} dispatch={dispatch} notify={notify} onClose={()=>setModal(null)}/>} {modal?.type==='settings'&&<SettingsModal teacher={teacher} onLogout={signOutTeacher} onClose={()=>setModal(null)}/>} {modal?.type==='teacher-login'&&<TeacherLoginModal onSuccess={finishTeacherLogin} onClose={()=>setModal(null)}/>} {toast&&<div className="toast" role="status"><CheckCircle2 size={18}/>{toast}</div>}
  </div>;
}
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
