import {useEffect,useRef,useState} from 'react';
let database;
async function openDB(){if(database)return database;database=await new Promise((resolve,reject)=>{const req=indexedDB.open('kouyu-recordings',1);req.onupgradeneeded=()=>req.result.createObjectStore('audio');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});return database;}
export async function saveAudio(id,blob){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction('audio','readwrite');tx.objectStore('audio').put(blob,id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
export async function getAudio(id){const db=await openDB();return new Promise((resolve,reject)=>{const req=db.transaction('audio').objectStore('audio').get(id);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
export function useSpeech(){const [playing,setPlaying]=useState(false),[error,setError]=useState('');const token=useRef(0);const stop=()=>{token.current++;window.speechSynthesis?.cancel();setPlaying(false);};useEffect(()=>()=>{token.current++;window.speechSynthesis?.cancel();},[]);
  function speak(text,rate=1,onEnd){stop();setError('');if(!window.speechSynthesis||!window.SpeechSynthesisUtterance){setError('此浏览器不支持语音播放，请换用 Chrome 或 Edge。');return;}const current=token.current;const utterance=new SpeechSynthesisUtterance(text);utterance.lang='en-US';utterance.rate=rate;const voice=window.speechSynthesis.getVoices().find(v=>v.lang==='en-US');if(voice)utterance.voice=voice;utterance.onstart=()=>{if(current===token.current)setPlaying(true);};utterance.onend=()=>{if(current===token.current){setPlaying(false);onEnd?.();}};utterance.onerror=e=>{if(current===token.current){setPlaying(false);if(!['canceled','interrupted'].includes(e.error))setError('语音播放失败，请确认设备已安装英语语音后重试。');}};window.speechSynthesis.speak(utterance);}
  return {playing,error,speak,stop};
}
export function useRecorder(onSave){const [status,setStatus]=useState('idle'),[seconds,setSeconds]=useState(0),[error,setError]=useState('');const recorder=useRef(null),stream=useRef(null),mounted=useRef(true),started=useRef(0);
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;if(recorder.current){recorder.current.onstop=null;if(recorder.current.state==='recording')recorder.current.stop();}stream.current?.getTracks().forEach(t=>t.stop());};},[]);
  useEffect(()=>{if(status!=='recording')return;const timer=setInterval(()=>{setSeconds(Math.floor((Date.now()-started.current)/1000));if(Date.now()-started.current>=120000&&recorder.current?.state==='recording')recorder.current.stop();},250);return()=>clearInterval(timer);},[status]);
  async function start(){if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){setError('此浏览器不支持录音，请使用 HTTPS 或本地预览，并换用 Chrome / Edge。');return;}setError('');setStatus('requesting');try{const incoming=await navigator.mediaDevices.getUserMedia({audio:true});if(!mounted.current){incoming.getTracks().forEach(t=>t.stop());return;}stream.current=incoming;const chunks=[];const rec=new MediaRecorder(incoming);recorder.current=rec;rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};rec.onerror=()=>{setError('录音中断，请重新录制。');setStatus('idle');incoming.getTracks().forEach(t=>t.stop());};rec.onstop=async()=>{incoming.getTracks().forEach(t=>t.stop());if(!mounted.current)return;setStatus('saving');const duration=Math.round((Date.now()-started.current)/1000);if(duration<1||!chunks.length){setError('录音太短，请至少录制 1 秒。');setStatus('idle');return;}try{await onSave(new Blob(chunks,{type:rec.mimeType}),duration);if(mounted.current)setStatus('saved');}catch{if(mounted.current){setStatus('idle');setError('录音保存失败，请检查浏览器存储空间后重试。');}}};started.current=Date.now();setSeconds(0);rec.start();setStatus('recording');}catch(e){if(mounted.current){setStatus('idle');setError(e.name==='NotAllowedError'?'未获得麦克风权限。请在浏览器设置中允许录音后重试。':'未找到可用麦克风，或麦克风正被其他应用占用。');}}}
  function stop(){if(recorder.current?.state==='recording')recorder.current.stop();}return {status,seconds,error,start,stop};
}
