import React,{useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Bookmark,Check,CheckCircle2,Headphones,Leaf,MessageCircle,Mic2,Play,Repeat2,Send,ShieldCheck,Sparkles,Square,Volume2} from 'lucide-react';
import {lessons,respondToDialogue} from './model.mjs';
import {useSpeech,useRecorder,saveAudio} from './media.js';
import {uploadAudio} from './api.js';
import {Button,Tag,Empty,PageHeading,AudioPlayback,clock,date} from './ui.jsx';
export function Practice({state,dispatch,initialStep='listening',go,notify,account}){
  const lesson=lessons.find(l=>l.id===state.activeLesson);const [step,setStep]=useState(initialStep);const steps=[['listening','精听输入',Headphones],['speaking','跟读练习',Mic2],['dialogue','情景表达',MessageCircle],['review','复盘与提交',CheckCircle2]];
  function advance(next){dispatch({type:'progress',lesson:lesson.id,step});setStep(next);}
  return <><div className="practice-top"><button className="text-btn" onClick={()=>go('path')}><ArrowLeft size={15}/>返回学习路径</button><span><Tag>{lesson.level}</Tag> {lesson.category}</span></div><PageHeading eyebrow={lesson.english.toUpperCase()} title={lesson.title} description={lesson.goal}/><nav className="practice-steps" aria-label="练习环节">{steps.map(([id,title,Icon],i)=><button key={id} aria-current={step===id?'step':undefined} className={step===id?'active':state.progress[lesson.id]?.[id]?'done':''} onClick={()=>setStep(id)}><span>{state.progress[lesson.id]?.[id]?<Check size={17}/>:<Icon size={17}/>}</span><small>0{i+1}</small>{title}</button>)}</nav><div key={`${lesson.id}-${step}`}>{step==='listening'?<Listening lesson={lesson} state={state} dispatch={dispatch} next={()=>advance('speaking')}/>:step==='speaking'?<Speaking lesson={lesson} state={state} dispatch={dispatch} next={()=>setStep('dialogue')} notify={notify} account={account}/>:step==='dialogue'?<Dialogue lesson={lesson} dispatch={dispatch} next={()=>setStep('review')}/>:<Review lesson={lesson} state={state} dispatch={dispatch} go={go} retry={()=>setStep('speaking')} notify={notify}/>}</div></>;
}
function Listening({lesson,state,dispatch,next}){
  const [line,setLine]=useState(0),[translation,setTranslation]=useState(true),[rate,setRate]=useState(1),[loop,setLoop]=useState(false),[heard,setHeard]=useState(false);const speech=useSpeech();const loopRef=useRef(loop),rateRef=useRef(rate);loopRef.current=loop;rateRef.current=rate;
  function play(index){setLine(index);speech.speak(lesson.lines[index][0],rateRef.current,()=>{setHeard(true);if(loopRef.current)play(index);});}
return <div className="practice-grid"><section className="panel listening-panel"><div className="panel-title"><div><span className="eyebrow">LISTEN CLOSELY</span><h2>先听一遍，抓住重点</h2></div><Tag color="amber-tag">合成语音示范</Tag></div><div className="listening-console"><button className="play-round" aria-label={speech.playing?'停止播放':'播放当前句'} onClick={()=>speech.playing?speech.stop():play(line)}>{speech.playing?<Square size={20} fill="currentColor"/>:<Play size={23} fill="currentColor"/>}</button><div className={`waveform ${speech.playing?'playing':''}`}>{Array.from({length:45},(_,i)=><i key={i} style={{height:`${12+((i*17+9)%39)}px`,animationDelay:`${i%5*.12}s`}}/>)}</div><span className="console-count">{line+1}<small> / {lesson.lines.length} 句</small></span></div><div className="player-tools"><Button kind="ghost" aria-pressed={loop} onClick={()=>setLoop(!loop)}><Repeat2 size={15}/>{loop?'单句循环中':'单句循环'}</Button><label>语速 <select aria-label="播放语速" value={rate} onChange={e=>{speech.stop();setRate(Number(e.target.value));}}><option value="0.75">0.75×</option><option value="1">1.0×</option><option value="1.25">1.25×</option></select></label><Button kind="ghost" aria-pressed={translation} onClick={()=>setTranslation(!translation)}>{translation?'隐藏译文':'显示译文'}</Button></div>{speech.error&&<p className="error">{speech.error}</p>}<div className="transcript-lines">{lesson.lines.map(([en,cn],i)=><button key={en} className={i===line?'selected':''} onClick={()=>play(i)}><span>{String(i+1).padStart(2,'0')}</span><div><strong>{en}</strong>{translation&&<p>{cn}</p>}</div><Volume2 size={16}/></button>)}</div><div className="practice-footer"><small>{heard?'已播放示范，准备好就开始跟读。':'点击句子播放；无法播放时可先阅读字幕。'}</small><Button onClick={()=>{speech.stop();next();}}>已理解，开始跟读<ArrowRight size={15}/></Button></div></section><aside className="panel vocabulary"><span className="eyebrow">WORDS IN CONTEXT</span><h3>带走几个好用表达</h3>{lesson.words.map(([word,phonetic,meaning])=><div className="word" key={word}><div><strong>{word}</strong><small>{phonetic}</small><p>{meaning}</p></div><button aria-label={`${state.words.includes(word)?'取消收藏':'收藏'} ${word}`} aria-pressed={state.words.includes(word)} onClick={()=>dispatch({type:'word',word})}><Bookmark size={17} fill={state.words.includes(word)?'currentColor':'none'}/></button></div>)}<div className="soft-note"><Leaf size={18}/><p>先理解意思，再关注表达。点亮书签，把新词留给下次复习。</p></div></aside></div>;
}
function Speaking({lesson,state,dispatch,next,notify,account}){
  const [line,setLine]=useState(1),[lastId,setLastId]=useState('');const speech=useSpeech();
  const recorder=useRecorder(async(blob,duration)=>{const id=crypto.randomUUID(),text=lesson.lines[line][0],created=Date.now(),cloudAudio=account?.role==='student';await saveAudio(id,blob);if(cloudAudio)await uploadAudio(id,blob,{lesson:lesson.id,text,duration});dispatch({type:'record',record:{id,lesson:lesson.id,text,duration,created,submitted:false,cloudAudio}});dispatch({type:'progress',lesson:lesson.id,step:'speaking'});setLastId(id);notify(cloudAudio?'录音已加密传输并保存到 KV 云端':'录音已保存在本机；登录学生账号后可使用云端录音');});
  const busy=['recording','requesting','saving'].includes(recorder.status),recordings=state.records.filter(r=>r.lesson===lesson.id);
  return <div className="practice-grid"><section className="panel speaking-panel"><div className="panel-title"><span className="eyebrow">MAKE IT YOUR OWN</span><Tag>{line+1} / {lesson.lines.length} 句</Tag></div><div className="sentence-nav"><button aria-label="上一句" disabled={line===0||busy} onClick={()=>{speech.stop();setLine(line-1);setLastId('');}}><ArrowLeft/></button><div><h2>{lesson.lines[line][0]}</h2><p>{lesson.lines[line][1]}</p></div><button aria-label="下一句" disabled={line===lesson.lines.length-1||busy} onClick={()=>{speech.stop();setLine(line+1);setLastId('');}}><ArrowRight/></button></div><Button kind="soft" disabled={busy} onClick={()=>speech.speak(lesson.lines[line][0],.85)}><Volume2 size={16}/>听合成示范</Button>{speech.error&&<p className="error">{speech.error}</p>}<div className={`record-area ${recorder.status==='recording'?'is-recording':''}`}><div className="record-orbit"><button disabled={['requesting','saving'].includes(recorder.status)} aria-label={recorder.status==='recording'?'停止并保存录音':'开始录音'} onClick={()=>{speech.stop();recorder.status==='recording'?recorder.stop():recorder.start();}}>{recorder.status==='recording'?<Square fill="currentColor"/>:<Mic2 size={28}/>}</button></div><h3>{({idle:'准备好了，就开口吧',requesting:'等待麦克风授权',recording:`正在录音 ${clock(recorder.seconds)}`,saving:'正在上传录音…',saved:'很好，录音已保存到云端'})[recorder.status]}</h3><p>{account?.role==='student'?'最长 2 分钟 · KV 云端保存并保留本机缓存':'最长 2 分钟 · 当前仅保存在本机，登录学生账号后可云端同步'}</p></div>{recorder.error&&<p className="error" role="alert">{recorder.error}</p>}{lastId&&<div className="record-result"><div><CheckCircle2 size={18}/><strong>回听自己的表达</strong><Tag>待人工复核</Tag></div><AudioPlayback id={lastId}/><p>语音评测尚未接入，暂不生成分数。先检查是否清楚、完整地说出了这句话。</p></div>}<div className="practice-footer"><small>本课已保存 {recordings.length} 段录音</small><Button disabled={busy} onClick={()=>{speech.stop();next();}}>{recordings.length?'继续情景表达':'先进入情景表达'}<ArrowRight size={15}/></Button></div></section><aside className="panel vocabulary"><span className="eyebrow">A SMALL CHECKLIST</span><h3>回听时，留意这三点</h3>{[['01','意思完整','有没有漏掉影响意思的词？'],['02','停顿自然','试着按意群停顿，不必逐词说。'],['03','交流清楚','重点词是否说得清楚、容易理解？']].map(([n,t,d])=><div className="tip-row" key={n}><span>{n}</span><div><b>{t}</b><p>{d}</p></div></div>)}<div className="soft-note"><ShieldCheck size={18}/><p>没有可靠识别结果时不评分。一次录音也不能代表你的全部口语能力。</p></div></aside></div>;
}
function Dialogue({lesson,dispatch,next}){
  const [step,setStep]=useState(0),[input,setInput]=useState(''),[hint,setHint]=useState(false),[done,setDone]=useState(false),[messages,setMessages]=useState([{who:'partner',text:lesson.prompts[0]}]);const end=useRef();
  useEffect(()=>{if(messages.length>1)end.current?.scrollIntoView({block:'nearest'});},[messages.length]);
  function send(e){e.preventDefault();if(!input.trim()||done)return;const answer=respondToDialogue(lesson,step,input.trim());setMessages(m=>[...m,{who:'me',text:input.trim()},{who:'partner',text:answer.text}]);setStep(answer.step);setDone(answer.done);setInput('');setHint(false);if(answer.done)dispatch({type:'progress',lesson:lesson.id,step:'dialogue'});}
  return <div className="practice-grid"><section className="panel chat"><div className="chat-head"><span className="partner-icon"><MessageCircle size={21}/></span><div><h3>{lesson.category}练习伙伴</h3><small>文字角色扮演 · 规则示范</small></div><Tag color="amber-tag">AI 语音待接入</Tag></div><div className="chat-messages" aria-live="polite">{messages.map((m,i)=><div className={`message ${m.who}`} key={i}><small>{m.who==='me'?'你':'练习伙伴'}</small><p>{m.text}</p></div>)}<div ref={end}/></div>{done?<div className="chat-finish"><CheckCircle2/><div><b>三个沟通目标已覆盖</b><small>匹配关键词仅用于引导流程，不代表语言能力评分。</small></div><Button onClick={next}>进入复盘<ArrowRight size={15}/></Button></div>:<><div className="hint-row"><button className="text-btn" onClick={()=>setHint(!hint)}><Sparkles size={15}/>{hint?'收起提示':'需要一点提示？'}</button>{hint&&<p>{lesson.hints[step]}</p>}</div><form className="chat-compose" onSubmit={send}><input value={input} onChange={e=>setInput(e.target.value)} maxLength={500} aria-label="输入英语回答" placeholder="用英语表达你的想法…"/><Button type="submit" disabled={!input.trim()} aria-label="发送回答"><Send size={18}/></Button></form></>}</section><aside className="panel vocabulary"><span className="eyebrow">YOUR MISSION</span><h3>这次交流，试着做到</h3><p className="muted">{lesson.goal}</p><div className="mission-list">{lesson.goals.map((g,i)=><div className={step>i?'done':''} key={g}><span>{step>i?<Check size={14}/>:i+1}</span>{g}</div>)}</div><div className="progress-label"><span>沟通目标</span><b>{step} / {lesson.goals.length}</b></div><div className="progress-track"><i style={{width:`${step/lesson.goals.length*100}%`}}/></div><div className="soft-note"><MessageCircle size={19}/><p>现在可体验文字对话流程。真实 AI 追问、语音输入和纠错需要后续服务接入。</p></div></aside></div>;
}
function Review({lesson,state,dispatch,go,retry,notify}){
  const records=state.records.filter(r=>r.lesson===lesson.id),[id,setId]=useState(records[0]?.id||''),[reflection,setReflection]=useState(''),[task,setTask]=useState('');const tasks=state.tasks.filter(t=>t.published&&t.lesson===lesson.id),allDone=['listening','speaking','dialogue'].every(s=>state.progress[lesson.id]?.[s]),record=records.find(r=>r.id===id);
  return <div className="practice-grid"><section className="panel review-sheet"><span className="eyebrow">REFLECT & GROW</span><h2>留下一次表达，也留下一个发现</h2><p className="muted">听一听，想一想：下次你准备怎样说得更好？</p>{records.length?<><label className="field">选择本次录音<select value={id} onChange={e=>setId(e.target.value)}>{records.map((r,i)=><option key={r.id} value={r.id}>录音 {records.length-i} · {date(r.created)} · {clock(r.duration)}</option>)}</select></label><AudioPlayback id={id}/>{record&&<blockquote>{record.text}</blockquote>}<div className="notice"><ShieldCheck size={18}/>发音和流利度等待评测 / 人工反馈，当前无机器成绩。</div><label className="field">我的复盘<textarea value={reflection} onChange={e=>setReflection(e.target.value)} maxLength={600} placeholder="例如：选座位时能完整表达，但 aisle 还需要多听几遍。"/></label><label className="field">提交到课堂任务<select value={task} onChange={e=>setTask(e.target.value)}><option value="">暂不提交，只保存复盘</option>{tasks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><small className="muted">录音保存在私有 KV，任务、复盘和提交关系同步到 D1，可跨设备回放。</small></>:<Empty icon={Mic2} title="还没有可复盘的录音" action={<Button onClick={retry}>录下第一句话<Mic2 size={16}/></Button>}>请先在跟读环节保存一段真实录音。</Empty>}{records.length>0&&<div className="form-footer"><Button kind="outline" onClick={retry}>再练一次</Button><Button disabled={!reflection.trim()} onClick={()=>{dispatch({type:'review',id:`self-${id}`,review:{text:reflection,created:Date.now()}});if(task)dispatch({type:'submit',id,task});if(allDone)dispatch({type:'progress',lesson:lesson.id,step:'review'});notify(task?'已提交，可在教师工作台批阅':'复盘已保存');go('report');}}>保存复盘{task?'并提交':''}<Check size={16}/></Button></div>}</section><aside className="panel vocabulary"><h3>本课练习进度</h3><div className="mission-list">{[['listening','理解示范表达'],['speaking','保存真实录音'],['dialogue','完成三个沟通目标']].map(([key,title])=><div className={state.progress[lesson.id]?.[key]?'done':''} key={key}><span>{state.progress[lesson.id]?.[key]?<Check size={14}/>:'·'}</span>{title}</div>)}</div><p className="muted">完成前三个环节并保存复盘后，该学习单元会标记为完成。</p><Button kind="outline full" onClick={()=>go('path')}>返回学习路径</Button></aside></div>;
}
