import React,{useState} from 'react';
import {ArrowUpRight,ArrowRight,ArrowLeft,AudioLines,BookOpen,Bookmark,Check,CheckCircle2,Clock3,Coffee,Headphones,Leaf,MessageCircle,Mic2,Plane,Search,Sparkles,Target,Volume2,Repeat2} from 'lucide-react';
import {lessons,lessonProgress,recommendLesson} from './model.mjs';
import {useSpeech} from './media.js';
import {Button,Tag,Empty,SectionTitle,PageHeading,LessonIcon,LessonCard,AudioPlayback,clock,date} from './ui.jsx';

export function Home({state,go,select}){
  const active=lessons.find(l=>l.id===state.activeLesson),progress=lessonProgress(state,active.id);
  const days=new Set(state.records.map(r=>new Date(r.created).toLocaleDateString('zh-CN'))).size;
  const total=Object.values(state.progress).filter(p=>p.review).length;
  return <><div className="welcome"><div><p className="eyebrow">A LITTLE PRACTICE, EVERY DAY</p><h1>每一次开口，都更靠近自信<span>。</span></h1><p>听懂一句，练好一句，再把它用在真实的交流里。</p></div><div className="date-stamp"><span>{new Intl.DateTimeFormat('en',{month:'short'}).format(new Date()).toUpperCase()}</span><b>{new Date().getDate().toString().padStart(2,'0')}</b><small>{new Intl.DateTimeFormat('zh-CN',{weekday:'long'}).format(new Date())}</small></div></div>
    <div className="home-grid"><div><section className="hero"><div className="hero-copy"><div className="hero-label"><span className="dot"/>{state.diagnostic?'你的下一站':'从这里开始'}<span>UNIT 0{lessons.indexOf(active)+1}</span></div><h2>{active.title}</h2><p>{active.goal}</p><div className="hero-meta"><span>{active.level} 场景应用</span><span><Clock3 size={13}/>{active.minutes} 分钟</span><span>听 · 读 · 说</span></div><Button kind="white" onClick={()=>go(state.diagnostic?'practice':'diagnostic')}>{state.diagnostic?(progress?'继续本次练习':'开始今天的练习'):'诊断水平，开始练习'}<ArrowRight size={17}/></Button><small>{state.diagnostic?`${progress} / 4 个练习环节已完成`:'约 3 分钟了解目标，为你推荐起点'}</small></div><div className="hero-graphic" aria-hidden="true"><div className="orbit orbit-1"/><div className="orbit orbit-2"/><div className="orbit orbit-3"/><span className="flight-line"/><Plane className="hero-plane"/><div className="passport"><span>SPEAKING LAB</span><AudioLines/><strong>LET’S<br/>GO PLACES.</strong><i>YOUR VOICE. YOUR WORLD.</i></div><span className="bubble bubble-one"><Check size={14}/> Ready to speak</span><span className="bubble bubble-two">{active.hints[2]}</span></div></section>
    <div className="stats"><div><span className="stat-icon"><Mic2/></span><span><b>{state.records.length}<small> 次</small></b><label>已保存录音</label></span></div><div><span className="stat-icon amber"><Clock3/></span><span><b>{Math.ceil(state.records.reduce((n,r)=>n+r.duration,0)/60)}<small> 分钟</small></b><label>累计录音时长</label></span></div><div><span className="stat-icon lavender"><CheckCircle2/></span><span><b>{total}<small> 个</small></b><label>已完成学习单元</label></span></div></div>
    <SectionTitle eyebrow="STEP BY STEP" title="今天，把这一课练完整" action={<button className="text-btn" onClick={()=>go('path')}>学习路径<ArrowUpRight size={16}/></button>}/><div className="flow-cards">{[['听懂表达','听示范，捕捉关键信息','listening',Headphones],['模仿开口','录下自己的声音','speaking',Mic2],['用在对话里','带着目标，完成交流','dialogue',MessageCircle]].map(([title,desc,step,Icon],i)=><button className="flow-card" key={step} onClick={()=>go('practice',step)}><div><span className={`mini-icon step-${i}`}><Icon size={20}/></span><small>0{i+1}</small></div><h3>{title}</h3><p>{desc}</p><span className="flow-bottom">{state.progress[active.id]?.[step]?<><Check size={14}/>已完成</>:'进入练习'}<ArrowRight size={15}/></span></button>)}</div></div>
    <aside className="right-rail"><section className="panel daily"><div className="rail-title"><h3>我的学习节奏</h3><Leaf size={18}/></div><p>从今天开始，每次开口都算数。</p><div className="week">{['一','二','三','四','五','六','日'].map((day,i)=>{const now=new Date(),diff=(now.getDay()+6)%7,d=new Date(now);d.setDate(now.getDate()-diff+i);const done=state.records.some(r=>new Date(r.created).toDateString()===d.toDateString());return <div key={day}><small>{day}</small><span className={done?'done':i===diff?'today':''}>{done?<Check size={14}/>:i===diff?<span className="tiny-dot"/>:'·'}</span></div>;})}</div><div className="rail-foot"><strong>{days}<small> 个练习日</small></strong><span>持续积累</span></div></section><section className="panel readiness"><div className="rail-title"><h3>能力画像</h3><Tag>{state.diagnostic?'已完成自评':'待诊断'}</Tag></div><div className="readiness-visual"><div className="radar-lines"/><Target size={44}/></div><h4>{state.diagnostic?'知道起点，更好出发':'先认识现在的自己'}</h4><p>{state.diagnostic?'当前推荐基于目标与基础题，口语能力还需真实录音评测。':'用一个简短诊断，找到适合你的练习起点。'}</p><Button kind="outline full" onClick={()=>go('diagnostic')}>{state.diagnostic?'查看 / 更新诊断':'开始基础诊断'}<ArrowRight size={15}/></Button></section><section className="daily-tip"><span><Sparkles size={15}/>开口小贴士</span><p>先把意思表达完整，<br/>再把一句话说得更好。</p><small>Communication comes first.</small></section></aside></div>
    <SectionTitle eyebrow="EXPLORE & SPEAK" title="下一个场景，你来选择" action={<button className="text-btn" onClick={()=>go('library')}>全部资源<ArrowUpRight size={16}/></button>}/><div className="lesson-grid">{lessons.map(l=><LessonCard key={l.id} lesson={l} state={state} onClick={()=>select(l.id)}/>)}</div></>;
}
export function Diagnostic({state,dispatch,go}){
  const [step,setStep]=useState(0),[goal,setGoal]=useState(state.diagnostic?.goal||'travel'),[confidence,setConfidence]=useState(state.diagnostic?.confidence||'starting'),[answer,setAnswer]=useState(''),[done,setDone]=useState(false);const speech=useSpeech();
  function finish(){dispatch({type:'diagnose',value:{goal,confidence,answer,created:Date.now()}});setDone(true);speech.stop();}
  if(done){const l=lessons.find(l=>l.id===recommendLesson({goal,confidence,answer}));return <div className="center-sheet"><div className="success-icon"><Check/></div><p className="eyebrow">YOUR STARTING POINT</p><h1>找到你的第一站了</h1><p>根据学习目标、自评和一道听辨题，建议从这里开始。</p><div className="recommendation"><LessonIcon lesson={l}/><div><Tag>{l.level}</Tag><h2>{l.title}</h2><p>{l.goal}</p></div></div><div className="notice">这是学习起点建议，不是标准语言等级认证。发音、流利度等能力需接入语音评测后评估。</div><Button onClick={()=>go('practice')}>开始我的第一课<ArrowRight size={16}/></Button></div>;}
  return <div className="center-sheet diagnostic"><p className="eyebrow">GET TO KNOW YOU</p><h1>先了解你，再安排练习</h1><p>无需准备。用现在的真实感受，找到合适的起点。</p><div className="step-dots">{['学习目标','开口感受','基础听辨'].map((s,i)=><div className={i<=step?'active':''} key={s}><span>{i<step?<Check size={13}/>:i+1}</span>{s}</div>)}</div><h2>{['你最想在哪个场景开口？','现在，用英语交流的感觉如何？','听一听，旅客想要哪一种座位？'][step]}</h2>{step===0?<div className="options">{[['travel','旅行沟通','出行、问路、酒店与机场',Plane],['campus','校园生活','认识同学，参与讨论',Coffee],['opinion','观点表达','说出想法，给出理由',MessageCircle]].map(([id,title,desc,Icon])=><button key={id} className={goal===id?'selected':''} onClick={()=>setGoal(id)}><Icon/><div><b>{title}</b><small>{desc}</small></div><span className="radio-dot"/></button>)}</div>:step===1?<div className="options">{[['starting','需要一点支持','知道一些单词，但组织句子时容易卡住'],['comfortable','可以完成基本交流','能表达日常想法，希望更连贯自然']].map(([id,title,desc])=><button key={id} className={confidence===id?'selected':''} onClick={()=>setConfidence(id)}><div><b>{title}</b><small>{desc}</small></div><span className="radio-dot"/></button>)}</div>:<><Button kind="soft" onClick={()=>speech.speak('I would like a window seat, please.')}><Volume2 size={17}/>播放题目 · 合成示范</Button>{speech.error&&<p className="error">{speech.error}可选择跳过。</p>}<div className="options compact">{[['window','靠窗的座位'],['aisle','靠过道的座位'],['skip','暂时不确定 / 无法播放']].map(([id,text])=><button key={id} onClick={()=>setAnswer(id)} className={answer===id?'selected':''}>{text}<span className="radio-dot"/></button>)}</div></>}<div className="form-footer"><Button kind="ghost" onClick={()=>step?setStep(step-1):go('home')}><ArrowLeft size={16}/>{step?'上一步':'稍后再做'}</Button><Button disabled={step===2&&!answer} onClick={()=>step<2?setStep(step+1):finish()}>{step===2?'生成起点建议':'下一步'}<ArrowRight size={16}/></Button></div></div>;
}
export function Path({state,go,select}){return <><PageHeading eyebrow="YOUR LEARNING JOURNEY" title="一步一步，让表达更自然" description="建议顺序可以参考，学习节奏由你决定。"/><div className="path-layout"><div className="path-list"><section className={`path-item ${state.diagnostic?'complete':''}`}><span className="path-marker">{state.diagnostic?<Check/>:'0'}</span><div className="panel"><Tag>{state.diagnostic?'已完成':'建议先完成'}</Tag><h2>认识你的口语起点</h2><p>选择目标、自评，再完成一道基础听辨题。</p><Button kind="outline" onClick={()=>go('diagnostic')}>{state.diagnostic?'更新诊断':'开始基础诊断'}<ArrowRight size={15}/></Button></div></section>{lessons.map((l,i)=><section key={l.id} className={`path-item ${lessonProgress(state,l.id)===4?'complete':''}`}><span className="path-marker">{lessonProgress(state,l.id)===4?<Check/>:i+1}</span><div className="panel path-lesson"><div><Tag>{l.level} · {l.category}</Tag><h2>{l.title}</h2><p>{l.goal}</p><div className="path-steps">{[['listening','精听'],['speaking','跟读'],['dialogue','对话'],['review','复盘']].map(([id,name])=><span key={id} className={state.progress[l.id]?.[id]?'done':''}>{state.progress[l.id]?.[id]?<Check size={12}/>:<span className="tiny-dot"/>}{name}</span>)}</div><Button kind={state.activeLesson===l.id?'':'outline'} onClick={()=>select(l.id)}>{lessonProgress(state,l.id)?'继续 / 复练':'进入本课'}<ArrowRight size={15}/></Button></div><LessonIcon lesson={l} large/></div></section>)}</div><aside className="panel path-note"><Leaf/><h3>好的练习，需要一点循环</h3><p>先听懂，再模仿，然后尝试自己表达。复盘时，挑一个小问题带到下一次练习。</p><hr/><p>每个场景保留独立进度，可随时返回重练。</p><Tag>听 → 读 → 说 → 复盘</Tag></aside></div></>;}
export function LibraryPage({state,select,teacher=false,onCreate}){const [query,setQuery]=useState(''),[filter,setFilter]=useState('全部');const results=lessons.filter(l=>(filter==='全部'||l.category===filter)&&`${l.title} ${l.english} ${l.category} ${l.words.flat().join(' ')}`.toLowerCase().includes(query.toLowerCase()));return <><PageHeading eyebrow={teacher?'TEACHING MATERIALS':'LISTEN. PRACTICE. EXPRESS.'} title={teacher?'让好素材，成为好练习':'从感兴趣的场景开始'} description="精选场景，配套字幕、词汇、跟读与对话目标。"/><div className="filter-bar"><div className="filter-tabs">{['全部',...lessons.map(l=>l.category)].map(f=><button className={filter===f?'active':''} key={f} onClick={()=>setFilter(f)}>{f}</button>)}</div><label className="search-input"><Search size={16}/><input aria-label="搜索资源" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索场景、主题或词汇"/></label></div>{results.length?<div className="lesson-grid">{results.map(l=><LessonCard key={l.id} lesson={l} state={state} onClick={()=>teacher?onCreate(l.id):select(l.id)}/>)}</div>:<Empty icon={Search} title="没有找到匹配的场景">试试“机场”“校园”或清除搜索条件。</Empty>}<div className="inline-note"><BookOpen size={16}/>{teacher?'选择素材即可创建教学任务。上传自有音视频将在资源服务接入后开放。':'当前 3 个场景均为原创练习文本，播放使用浏览器英语合成语音。'}</div></>;}
export function Tasks({state,select}){return <><PageHeading eyebrow="MY CLASSROOM" title="课堂里的练习，课后接着说" description="完成老师布置的任务，把录音和思考一起留下。"/><div className="task-list">{state.tasks.filter(t=>t.published).map(t=>{const l=lessons.find(l=>l.id===t.lesson),submitted=state.records.some(r=>r.task===t.id&&r.submitted);return <section className="panel task-card" key={t.id}><LessonIcon lesson={l}/><div><div className="task-meta"><Tag>{submitted?'已提交':'待练习'}</Tag>{t.sample&&<Tag color="neutral">示例任务</Tag>}<small>{t.group}{t.due?` · 截止 ${t.due}`:''}</small></div><h2>{t.title}</h2><p>{t.instruction}</p></div><Button kind="outline" onClick={()=>select(t.lesson)}>{submitted?'继续复练':'开始任务'}<ArrowRight size={15}/></Button></section>;})}</div></>;}
export function Report({state,select}){return <><PageHeading eyebrow="YOUR PRACTICE MATTERS" title="每一次练习，都留下痕迹" description="这里记录真实保存的录音、你的复盘和教师反馈。"/><div className="report-banner"><AudioLines size={38}/><div><h2>把进步交给持续练习</h2><p>已保存 {state.records.length} 段录音 · 完成 {Object.values(state.progress).filter(p=>p.review).length} 个单元</p></div><Tag>能力评测待接入</Tag></div>{state.records.length?<div className="record-list">{state.records.map(r=>{const l=lessons.find(l=>l.id===r.lesson);return <section className="panel record-card" key={r.id}><div className="panel-title"><div><Tag>{r.submitted?'已提交':'个人练习'}</Tag><h3>{l.title}</h3><small>{date(r.created)} · {clock(r.duration)}</small></div><Button kind="outline" onClick={()=>select(r.lesson)}>复练<Repeat2 size={15}/></Button></div><p>{r.text}</p><AudioPlayback id={r.id}/>{state.reviews[`self-${r.id}`]&&<div className="feedback-block"><b>我的复盘</b><p>{state.reviews[`self-${r.id}`].text}</p></div>}{state.reviews[r.id]&&<div className="feedback-block teacher-feedback"><b>教师点评 · {clock(state.reviews[r.id].at)}</b><p>{state.reviews[r.id].text}</p></div>}</section>;})}</div>:<Empty icon={AudioLines} title="你的第一段录音，会从这里开始" action={<Button onClick={()=>select(state.activeLesson)}>去练习<ArrowRight size={16}/></Button>}>学习记录会根据实际操作生成，不显示预设分数。</Empty>}</>;}
export function Words({state,dispatch,go}){const speech=useSpeech();const words=lessons.flatMap(l=>l.words).filter(w=>state.words.includes(w[0]));return <><PageHeading eyebrow="COLLECT GOOD EXPRESSIONS" title="把好表达，留给下一次开口" description={`${words.length} 个已收藏表达 · 来自你的精听练习`}/>{speech.error&&<p className="error">{speech.error}</p>}{words.length?<div className="word-grid">{words.map(([word,phonetic,meaning])=><article className="panel word-card" key={word}><div><h2>{word}</h2><button aria-label={`取消收藏 ${word}`} onClick={()=>dispatch({type:'word',word})}><Bookmark size={18} fill="currentColor"/></button></div><small>{phonetic}</small><p>{meaning}</p><Button kind="soft" onClick={()=>speech.speak(word,.8)}><Volume2 size={15}/>听发音</Button></article>)}</div>:<Empty icon={Bookmark} title="生词本还是空的" action={<Button onClick={()=>go('practice')}>去精听，收藏表达<ArrowRight size={15}/></Button>}>在精听页面点亮书签，把喜欢的表达收进来。</Empty>}</>;}
